import type { NextPage } from "next";
import Head from "next/head";
import { CustomForm } from "src/components/CustomForm";
import { List } from "src/components/List";
import { Timer } from "src/components/Timer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Alura Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <CustomForm />
        {/* eslint-disable-next-line react/jsx-no-bind */}
        <List />
        {/* eslint-disable-next-line react/jsx-no-bind */}
        <Timer />
      </main>
    </div>
  );
};

export default Home;
