import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { CustomForm } from "src/components/CustomForm";
import { List } from "src/components/List";
import { ITask } from "src/types/task";
import { Timer } from "src/components/Timer";

const Home: NextPage = () => {
  const [tasks, setTasks] = useState<ITask[]>([]);
  const [selected, setSelected] = useState<ITask>();

  function selectTask(selectedTask: ITask) {
    setSelected(selectedTask);
    setTasks((previousTasks) =>
      previousTasks.map((task) => ({
        ...task,
        selected: task.id === selectedTask.id,
      })),
    );
  }

  function finishTask() {
    if (selected) {
      setSelected(undefined);
      setTasks((previousTasks) =>
        previousTasks.map((task) => {
          if (task.id === selected.id) {
            return {
              ...task,
              selected: false,
              completed: true,
            };
          }
          return task;
        }),
      );
    }
  }

  return (
    <div>
      <Head>
        <title>Alura Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <CustomForm setTasks={setTasks} />
        {/* eslint-disable-next-line react/jsx-no-bind */}
        <List tasks={tasks} selectTask={selectTask} />
        {/* eslint-disable-next-line react/jsx-no-bind */}
        <Timer selected={selected} finishTask={finishTask} />
      </main>
    </div>
  );
};

export default Home;
